/*
  This file was automatically generated by "playwright-browser-unit".
  Any modifications made to this file may be overwritten.
*/
import { evaluateTest, SourceMap } from "playwright-browser-unit";

import { test } from "@playwright/test";

test.describe("browser tests", () => {

  test("workers available", async ({ page }) => {
    await page.goto("http://localhost:3000/test");
    await evaluateTest(page, "workers available", sourceMaps);
  });

});

const sourceMaps: SourceMap[] = [
  {
    url: "webpack-internal:///(app-pages-browser)/./app/test/page.tsx",
    sourceMapUrl: "data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiKGFwcC1wYWdlcy1icm93c2VyKS8uL2FwcC90ZXN0L3BhZ2UudHN4IiwibWFwcGluZ3MiOiI7Ozs7Ozs7O0FBRThEO0FBRTlEQSxxRUFBSUEsQ0FBQyxxQkFBcUI7SUFDeEJDLHVFQUFNQSxDQUFDLE9BQU9DLFdBQVcsYUFBYUMsSUFBSSxDQUFDO0FBQzdDO0FBRWUsU0FBU0M7SUFDdEIscUJBQ0UsOERBQUNDO2tCQUFLOzs7Ozs7QUFJVjtLQU53QkQiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly9fTl9FLy4vYXBwL3Rlc3QvcGFnZS50c3g/YjM5YiJdLCJzb3VyY2VzQ29udGVudCI6WyJcInVzZSBjbGllbnRcIjtcblxuaW1wb3J0IHsgdGVzdCwgZXhwZWN0IH0gZnJvbSBcInBsYXl3cmlnaHQtYnJvd3Nlci11bml0L2Jyb3dzZXJcIlxuXG50ZXN0KFwid29ya2VycyBhdmFpbGFibGVcIiwgKCkgPT4ge1xuICBleHBlY3QodHlwZW9mIFdvcmtlciAhPT0gXCJ1bmRlZmluZWRcIikudG9CZSh0cnVlKTtcbn0pXG5cbmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIEhvbWUoKSB7XG4gIHJldHVybiAoXG4gICAgPG1haW4+XG4gICAgICBUZXN0IHBhZ2VcbiAgICA8L21haW4+XG4gICk7XG59XG4iXSwibmFtZXMiOlsidGVzdCIsImV4cGVjdCIsIldvcmtlciIsInRvQmUiLCJIb21lIiwibWFpbiJdLCJzb3VyY2VSb290IjoiIn0="
  },
]

